### ISSUE TITLE
Consolidate KFS Predictor and MM Predictor schema

### ISSUE THREAD

**Issue by pvaneck** [kserve/modelmesh-serving#12]
This is a parent issue for this overall effort. The goal here is to figure out how we can merge and evolve the two different specs moving forward. 

Sub issues:

- https://github.com/kserve/modelmesh-serving/issues/4.

**Comment by pvaneck** [comment]
To show the general structure of a KFS Predictor and what fields it exposes to the end user, I've compiled a list.

**PredictorSpec**
```
SKLearn *SKLearnSpec 
XGBoost *XGBoostSpec
Tensorflow *TFServingSpec
PyTorch *TorchServeSpec
Triton *TritonSpec
ONNX *ONNXRuntimeSpec
PMML *PMMLSpec
LightGBM *LightGBMSpec
...

PodSpec (35 fields)
ComponentExtensionSpec (7 fields)
```

**ComponentExtensionSpec**
```
MinReplicas *int 
MaxReplicas int
ContainerConcurrency *int64
TimeoutSeconds *int64
CanaryTrafficPercent *int64 
Logger *LoggerSpec
Batcher *Batcher
```

**PodSpec**
```
Volumes []v1.Volume 
InitContainers []v1.Container 
Containers []v1.Container 
EphemeralContainers []v1.EphemeralContainer 
RestartPolicy v1.RestartPolicy 
TerminationGracePeriodSeconds *int64 
ActiveDeadlineSeconds *int64 
DNSPolicy v1.DNSPolicy 
NodeSelector map[string]string 
ServiceAccountName string 
DeprecatedServiceAccount string 
AutomountServiceAccountToken *bool 
NodeName string 
HostNetwork bool 
HostPID bool 
HostIPC bool
ShareProcessNamespace *bool 
SecurityContext *v1.PodSecurityContext 
ImagePullSecrets []v1.LocalObjectReference 
Hostname string 
Subdomain string 
Affinity *v1.Affinity 
SchedulerName string 
Tolerations []v1.Toleration 
HostAliases []v1.HostAlias 
PriorityClassName string 
Priority *int32 
DNSConfig *v1.PodDNSConfig 
ReadinessGates []v1.PodReadinessGate 
RuntimeClassName *string 
EnableServiceLinks *bool 
PreemptionPolicy *v1.PreemptionPolicy 
Overhead v1.ResourceList 
TopologySpreadConstraints []v1.TopologySpreadConstraint 
SetHostnameAsFQDN *bool 
```

Where each predictor type (e.g Sklearn) has the following fields:
```
StorageURI *string 
RuntimeVersion *string
ProtocolVersion *constants.InferenceServiceProtocol 
v1.Container 
```

Where v1.Container is
```
Name string 
Image string 
Command []string 
Args []string 
WorkingDir string 
Ports []ContainerPort 
EnvFrom []EnvFromSource 
Env []EnvVar 
Resources ResourceRequirements 
VolumeMounts []VolumeMount 
VolumeDevices []VolumeDevice 
LivenessProbe *Probe 
ReadinessProbe *Probe 
StartupProbe *Probe 
Lifecycle *Lifecycle 
TerminationMessagePath string 
TerminationMessagePolicy TerminationMessagePolicy 
ImagePullPolicy PullPolicy 
SecurityContext *SecurityContext 
Stdin bool 
StdinOnce bool 
TTY bool 
```

**Comment by pvaneck** [comment]
Comparatively, the MM Predictor Spec is fairly simple:

```
apiVersion: serving.kserve.io/v1alpha1
kind: Predictor
metadata:
  name: my-mnist-predictor
spec:
  modelType:
    name: tensorflow
    version: "1.15" # Optional
  runtime: # Optional
    name: triton-2.x
  path: my_models/mnist-tf
  storage:
    s3:
      secretKey: my_storage
      bucket: my_bucket
```
