### ISSUE TITLE
ProtocolVersion required when deploying Isvc with old format

### ISSUE THREAD

**Issue by pvaneck** [kserve/modelmesh-serving#173]
This works:

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: example-sklearn-isvc
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
    serving.kserve.io/secretKey: localMinIO
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: s3://modelmesh-example-models/sklearn/mnist-svm.joblib
```

while: 

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: example-sklearn-isvc
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
    serving.kserve.io/secretKey: localMinIO
spec:
  predictor:
    sklearn:
      storageUri: s3://modelmesh-example-models/sklearn/mnist-svm.joblib
```

this does not. 

In the second case, `getRuntimesSupportingPredictor()` isn't returning anything unless something like `protocolVersion: grpc-v2` is explicitly specified. 

The old format should still be able to find a runtime like in the first case even if no protocolVersion is specified by the user.
