### ISSUE TITLE
Add the ability to read the etcd certificates/key from a different secret or actual file

### ISSUE THREAD

**Issue by OvervCW** [kserve/modelmesh-serving#204]
We would like to use cert-manager to generate server and client certificates for etcd. It generates secrets that look like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  ...
type: kubernetes.io/tls
data:
  ca.crt: "..."
  tls.crt: "..."
  tls.key: "..."
```

ModelMesh in turn requires the etcd parameters to be configured through a secret that looks like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  ...
stringData: |
  etcd_connection: |
    {
      ...
      "certificate_file": "...",
      "client_certificate_file": "...",
      "client_key_file": "..."
    }
```

I expected to be able to mount the cert-manager secret in the ModelMesh controller pod (e.g. at `/etc/private/tls/etcd`) and then use these fields in `etcd_connection` to refer to paths like `/etc/private/tls/etcd/tls.crt`. However, it turns out that these `_file` parameters are actually interpreted by ModelMesh as keys in the same secret as the one containing the `etcd_connection`.

Unfortunately there is no way to combine the `etcd_connection` data into the cert-manager generated secret, so this means that we can only use certificates that have been directly embedded into the etcd secret. For now we've worked around this by generating the certificates differently, but we'd really prefer to use cert-manager.

I would like to propose one of the following solutions:

* Allow `_file` fields to either refer to a key in the secret (for backwards compatibility) or a path local to the controller pod.
* Add a parameter that allows `_file` fields to refer to keys in a different secret (like a cert-manager generated one).
