### ISSUE TITLE
onnx model not able to load

### ISSUE THREAD

**Issue by Agarwal-Saurabh** [kserve/modelmesh-serving#216]
Facing issue while loading the onnx based model in triton runtime.

Modelmesh version -0.9
triton-runtime - 2.x
kserve - 0.9

`ERROR	Triton Adapter.Triton Adapter Server.Load Model	Triton failed to load model	{"model_id": "example-onnx-predictor__ksp-c73d49c26f", "error": "rpc error: code = InvalidArgument desc = load failed for model 'example-onnx-predictor__ksp-c73d49c26f': version 1: Internal: onnx runtime error 1: Load model from /models/_triton_models/example-onnx-predictor__ksp-c73d49c26f/1/model.onnx failed:/workspace/onnxruntime/onnxruntime/core/graph/model.cc:111 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&) Unknown model file format version.\n;\n"}`

**Comment by njhill** [comment]
@Agarwal-Saurabh what does the model storage layout look like. Have you tried to load the model in a standalone Triton container?

**Comment by Agarwal-Saurabh** [comment]
I didn't got , what do you mean by standalone tiriton. 

```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: onnx-example
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      storage:
        key: localMinIO
        path: onnx/model.onnx
        parameters:
          bucket: modelmesh-test
```

This is what I am using as a part of deployment. 

model storage is under s3
onnx - > model.onnx.     @njhill
