### ISSUE TITLE
Serving a PyTorch model

### ISSUE THREAD

**Issue by MLHafizur** [kserve/modelmesh-serving#239]
I am trying to deploy a PyTorch model on Minikube. My manifest is like:

```
kubectl apply -f - <<EOF
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: example-pytorch-isvc
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      storageUri: /root/hafizur/pytorch-model/model.pt
EOF
```

Which is not working. `kubectl get isvc` give output like:
```
NAME                   URL                                                 READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION                    AGE
example-pytorch-isvc                                                                                                                                              13s
```

Have you ever tried to deploy PyTorch Model?
Can you deploy it without TorchScript?

@njhill Looking forward to your help.
