### ISSUE TITLE
ONNX model ::  Failed to load Model due to adapter error: Error calling stat on model file

### ISSUE THREAD

**Issue by MLHafizur** [kserve/modelmesh-serving#247]
Trying to deploy a PyTorch model in ONNX format on Azure AKS cluster namespace. Steps I followed:

1. Edited the existing storage-config file:  `kubectl edit secret storage-config -n modelmesh-serving-dev`, removed all S3 related information and replaces with azure blob storage info's:
```
 kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"storage-config","namespace":"modelmesh-serving-dev"},"stringData":{"localMinIO":"{\n  \"type\": \"azure\",\n  \"account_name\": \"____\",\n  \"container\": \"models\",\n  \"connection_string\": \"https://____.blob.core.windows.net/models? ____-"\n}\n"}}
```

2.  Applied the following inferenceservice manifest:
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: example-onnx-isvc
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      storage:
        key: localMinIO
        path: onxx-models/text-classify.onnx
```

3. Triton runtimes seems up and running. But no isvc url with the status False. kubectl describe isvc giving the following error:
```
 Last Failure Info:
      Location:             99f56d-2vkbn
      Message:              Failed to load Model due to adapter error: Error calling stat on model file: stat /models/example-onnx-isvc__isvc-4d89164c21/text-classify.onnx: no such file or directory
      Model Revision Name:  example-onnx-isvc__isvc-4d89164c21
      Reason:               ModelLoadFailed
```

I also tried with storageUri parameter option and got same error:
```
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      storageUri: https://d_____rsv3.blob.core.windows.net/models/onxx-models/text-classify.onnx
```
What am I missing?

Why does the path is weird? The model path is models/onxx-models/text-classify.onnx 
Why the revision name is in the path tree?

What is the solution? Am I heading to the right direction to successfully deploy a PyTorch model in ONNX format?
@njhill please help.
