### ISSUE TITLE
Can't create InferenceService

### ISSUE THREAD

**Issue by vulong3896** [kserve/modelmesh-serving#287]
## Overview

I am trying to deploy Model mesh on my company cluster but got this error when trying to create an InferenceService
```
Error from server (Exactly one of [SKLearn, XGBoost, Tensorflow, PyTorch, Triton, ONNX, PMML, LightGBM, Paddle, PodSpec] must be specified in PredictorSpec): error when creating "tableengine_isvc.yaml": admission webhook "inferenceservice.kserve-webhook-server.validator" denied the request: Exactly one of [SKLearn, XGBoost, Tensorflow, PyTorch, Triton, ONNX, PMML, LightGBM, Paddle, PodSpec] must be specified in PredictorSpec
```
Here is my yaml file for this InferenceService
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: example-onnx-mnist
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      storage:
        key: localMinIO
        path: onnx/mnist.onnx
```
I did exactly as in the installation doc here https://github.com/kserve/modelmesh-serving/blob/main/docs/install/install-script.md please help me out.
