### ISSUE TITLE
build a model runtime simulator to help measure elastic scaling efficiency with little system resource.

### ISSUE THREAD

**Issue by meijies** [kserve/modelmesh-serving#318]
# measure elastic scaling efficiency
A set of composite metrics including QPS(query per second), Error, ART(average response time) and so on. So we can determine the new optimization is valid or not.

# runtime simulator
the runtime load the yaml  file as model. this yaml file declare the resource that model should consume. blew is a example of yaml file.
``` yaml
resource:
  memory: 1M
  cpu: 5
time:
  load: 5 # second
  predict: 5 # second
```
