### ISSUE TITLE
ONNX model not loading

### ISSUE THREAD

**Issue by MLHafizur** [kserve/modelmesh-serving#327]
I have converted a PyTorch model to ONNX and  tried to inference on ModelMesh:

```
# load and prep the torch model to export it
torch_model = torch.load(os.path.join(input_path, "english_model_2023.pt"), map_location="cpu")
torch_model.eval()
# pick a sample batch as sample input
batches = [batch for batch in dataloader]
_batch = batches[0]
# inputs needed for the model
b_input_ids = _batch[0].to('cpu')
b_input_mask = _batch[1].to('cpu')
# create features dict
features = dict(input_ids = b_input_ids, attention_mask = b_input_mask)
# export the model
torch.onnx.export(torch_model, args=(features), f=os.path.join(input_path, "saved_onnx_model.onnx"), opset_version=15)
```
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: pipeline-poc-inference
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
    serving.kserve.io/secretKey: azureKey
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      storageUri: https://----.blob.core.windows.net/models/onnx_model_test/saved_onnx_model.onnx
```
Getting the following error:

`Message:   INVALID_ARGUMENT: Failed to load Model due to Triton runtime error: rpc error: code = InvalidArgument desc = load failed for model 'pipeline-poc-inference__isvc-954a7a73d2': version 1: Internal: onnx runtime error 1: Load model from /models/_triton_models/pipeline-poc-inference__isvc-954a7a73d2/1/model.onnx failed:/workspace/onnxruntime/onnxruntime/core/graph/model.cc:111 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&) Unknown model file format version.`

What could be the issue?
