### ISSUE TITLE
Auto Scaling Model Mesh Custom Runtime Service

### ISSUE THREAD

**Issue by sidharthkumarpradhan** [kserve/modelmesh-serving#331]
**Issue-1:**
We are trying to to autoscale the custom deployed runtime,, we have tried to specify the annotation and predictor parameters in Inference service manifest, but the scaling is not happening

example:

```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: demo
  namespace: model-mesh
  annotations:
    autoscaling.knative.dev/target: "10"
spec:
  predictor:
     minReplicas: 0
     containerConcurrency: 1
     scaleTarget: 10
     scaleMetric: concurrency
    model:
      modelFormat:
        name: custom-grpc-01
        version: "1"
      storageUri: <>
      runtime: muc-en-adv-mlserver-grpc-1.x.1
```

**Issue-2:**

Then we have tried to scale the custom runtime deployment by creating a HPA(Horizontal Pod Autoscaler), but though the Runtime pods are getting spun up , we are not able to distribute load across all the pods (Load Balancing is not happening),  and pods are getting terminated as soon as it's up.  Below is the HPA manifest that we are using. 

```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: model-mesh-es-adv-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: modelmesh-serving-muc-en-adv-mlserver-grpc-1.x.1
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
```

_Kindly help us to figure out an Autoscalin solution for Custom Runtime Model Mesh_. Thank you.
