### ISSUE TITLE
Failed calling webhook "inferenceservice.kserve-webhook-server.defaulter"

### ISSUE THREAD

**Issue by Kokkini** [kserve/modelmesh-serving#338]
**Describe the bug**
```Error from server (InternalError): error when creating "InferenceService.yaml": Internal error occurred: failed calling webhook "inferenceservice.kserve-webhook-server.defaulter": failed to call webhook: Post "https://kserve-webhook-server-service.kserve.svc:443/mutate-serving-kserve-io-v1beta1-inferenceservice?timeout=10s": service "kserve-webhook-server-service" not found```
**To Reproduce**
I ran the following code
```
RELEASE=release-0.10
git clone -b $RELEASE --depth 1 --single-branch https://github.com/kserve/modelmesh-serving.git
cd modelmesh-serving

kubectl create namespace modelmesh-serving
./scripts/install.sh --namespace modelmesh-serving --quickstart
kubectl apply -f InferenceService.yaml
```
Content of the InferenceService.yaml file:
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: example-sklearn-isvc
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
    serving.kserve.io/secretKey: localMinIO
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: s3://belletorus-modelmesh-test/model.joblib
```
Exactly like the quickstart tutorial except for the --namespace-scope-mode part. I removed that option.
I saw the bug after running: `kubectl apply -f InferenceService.yaml`. I can use Predictor without any problem but not InferenceService. It seems like InferenceService is trying to use KServe, which is not installed.

**Expected behavior**
I expect to see `predictor.serving.kserve.io/my-mnist-predictor created` after kubectl apply.

**Environment (please complete the following information):**
My k8s cluster is on AWS EKS. I once installed KServe in the past, but uninstalled it before installing ModelMesh Serving.

Thank you for your help!
