### ISSUE TITLE
Unable to load model on the Triton serving runtime

### ISSUE THREAD

**Issue by andreapairon** [kserve/modelmesh-serving#345]
Hi all,

I'm trying to load an `InferenceService` to the Triton serving runtime. When I do that, the `triton-adapter` container inside the triton serving runtime fails logging:

`ERROR   Triton Adapter.Triton Adapter Server.Load Model Triton failed to load model     {"model_id": "wf1-dati-contratto-token__isvc-c5b32eeb53", "error": "rpc error: code = Internal desc = failed to load 'wf1-dati-contratto-token__isvc-c5b32eeb53', no version is available"}`

However, if I try to load that model pinging directly the `triton` container  inside the triton serving on the port `8000`, I'm able to load it successfully...so maybe that's something wrong with my  `InferenceService` configuration.

This is my `InferenceService`:

```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: wf1-dati-contratto-token
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
        version: "1"
      runtime: triton-2.x
      storage:
        key: localMinIO
        path: WF1-dati-contratto-token
```
This is my MinIO folder structure:

![image](https://user-images.githubusercontent.com/16152588/225924534-df7f3ab9-f68e-42f3-8f1c-93a342a7a192.png)

I have my models bucket called `triton` then a folder called `WF1-dati-contratto-token` and finally the model config (`config.pbtx`t and `config.json` files) and the folder 1 container the `onnx` file.

From the `triton-adapter` logs, my MinIO instance is set correctly because model config files are downloaded:

```
1.6790529166725106e+09  INFO    Triton Adapter.Triton Adapter Server.Load Model Using model type        {"model_id": "wf1-dati-contratto-token__isvc-c5b32eeb53", "model_type": "onnx"}
1.6790529166725628e+09  DEBUG   Triton Adapter.Triton Adapter Server    Reading storage credentials
1.679052916672605e+09   DEBUG   Triton Adapter.Triton Adapter Server    found existing client in cache  {"type": "s3", "cacheKey": "s3|0x4602a3988d73d91"}
1.679052916703241e+09   DEBUG   Triton Adapter.Triton Adapter Server    found objects to download       {"type": "s3", "cacheKey": "s3|0x4602a3988d73d91", "path": "WF1-dati-contratto-token", "count": 3}
1.6790529167034016e+09  DEBUG   Triton Adapter.Triton Adapter Server    downloading object      {"type": "s3", "cacheKey": "s3|0x4602a3988d73d91", "path": "WF1-dati-contratto-token/1/model.onnx", "filename": "/models/wf1-dati-contratto-token__isvc-c5b32eeb53/WF1-dati-contratto-token/1/model.onnx"}
1.6790529167034292e+09  DEBUG   Triton Adapter.Triton Adapter Server    downloading object      {"type": "s3", "cacheKey": "s3|0x4602a3988d73d91", "path": "WF1-dati-contratto-token/config.json", "filename": "/models/wf1-dati-contratto-token__isvc-c5b32eeb53/WF1-dati-contratto-token/config.json"}
1.6790529167034502e+09  DEBUG   Triton Adapter.Triton Adapter Server    downloading object      {"type": "s3", "cacheKey": "s3|0x4602a3988d73d91", "path": "WF1-dati-contratto-token/config.pbtxt", "filename": "/models/wf1-dati-contratto-token__isvc-c5b32eeb53/WF1-dati-contratto-token/config.pbtxt"}
1.6790529184147723e+09  INFO    Triton Adapter.Triton Adapter Server.Load Model Deleting `name` field from config.pbtxt {"model_id": "wf1-dati-contratto-token__isvc-c5b32eeb53", "removed_name": "WF1-dati-contratto-token"}
```

Any help? Thanks in advance.
