### ISSUE TITLE
"Specified runtime name not recognised" error in Inference Service

### ISSUE THREAD

**Issue by xvnyv** [kserve/modelmesh-serving#352]
**Describe the bug**

When I create 1 custom serving runtime (SR1) and 1 inference service (IS1) that is to loaded onto SR1, I observe the expected behaviour whereby IS1 will have a failure message showing that the runtime is unhealthy and that it is waiting for the pod to become available while the serving runtime is scaling up. Once the serving runtime pod is fully running, IS1 will immediately be loaded and be in `Ready` state.

However, if I create a second serving runtime (SR2) and a second inference service (IS2) which is loaded onto SR2, what I observe is that IS2 will have a failure message saying that "`Specified runtime name not recognized`" while SR2 is in the midst of scaling up. Once the SR2 pod has all containers in Running state, IS2 does not immediately get loaded. Instead, it will only get loaded after a few minutes when the ModelMesh controller's predictor reconciler picks it up again. This behaviour is unexpected as I would think that SR2 and IS2 should follow the same behaviour as SR1 and IS1.

**To Reproduce**

Serving Runtime and Inference Service templates used when observing this error:
```yaml
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: mlserver-1
spec:
  builtInAdapter:
    memBufferBytes: 134217728
    modelLoadingTimeoutMillis: 90000
    runtimeManagementPort: 8001
    serverType: mlserver
  containers:
  - env:
    - name: MLSERVER_MODELS_DIR
      value: /models/
    - name: MLSERVER_GRPC_PORT
      value: "8001"
    - name: MLSERVER_HTTP_PORT
      value: "8002"
    - name: MLSERVER_LOAD_MODELS_AT_STARTUP
      value: "false"
    - name: MLSERVER_MODEL_NAME
      value: dummy-model
    - name: MLSERVER_HOST
      value: 127.0.0.1
    - name: MLSERVER_GRPC_MAX_MESSAGE_LENGTH
      value: "16777216"
    - name: MLSERVER_DEBUG
      value: "true"
    - name: MLSERVER_MODEL_PARALLEL_WORKERS
      value: "0"
    - name: MLSERVER_MODEL_IMPLEMENTATION
      value: mlserver_sklearn.SKLearnModel
    image: seldonio/mlserver:1.2.3
    name: mlserver
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 1Gi
  grpcDataEndpoint: port:8001
  grpcEndpoint: port:8085
  multiModel: true
  replicas: 1
  storageHelper:
    disabled: false
  supportedModelFormats:
  - autoSelect: true
    name: custom
    version: "1"
```

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
    serving.kserve.io/secretKey: default
  name: sklearn-1
spec:
  predictor:
    model:
      modelFormat:
        name: custom
        version: "1"
      name: ""
      resources: {}
      runtime: mlserver-1
      storageUri: <s3 uri>
```

The model used for the inference service is the SKLearn model trained on the MNIST dataset that is documented [here](https://github.com/kserve/modelmesh-serving/blob/main/docs/example-models.md#sklearn).

1. Within the same namespace, create 1 serving runtime with the above template. Then create 1 inference service with the above template after the serving runtime deployment has been created.
2. Wait for the serving runtime pod to have all containers in Running state and the inference service to be in Ready state.
3. Within the same namespace, create another serving runtime with the same template. Update the `spec.predictor.model.runtime` value in the inference service template to use the new serving runtime and create a new inference service.
4. The `Specified runtime name not recognized` error should appear in the status field of the new inference service.

**Expected behavior**

The new inference service should be showing the failure message `Waiting for runtime Pod to become available` with reason `RuntimeUnhealthy` instead of the message `Specified runtime name not recognized` and reason `RuntimeNotRecognized`.

**Screenshots**

Nil

**Environment (please complete the following information):**

- OS: [e.g. iOS] MacOS
- Browser [e.g. chrome, safari] Nil
- Version [e.g. 22] KServe v0.9.0, Kubernetes v1.24.10

ModelMesh (v0.9.0) was installed on a fresh cluster using the `--quickstart` option.

**Additional context**

Some observations that might be related to the problem:
- When I monitor the contents of etcd during the serving runtime and inference service creation, for the creation of SR1 and IS1, I noticed that the `instances` record was created before the `vmodels` and `registry` records. However, for the creation of SR2 and IS2, I noticed that the `vmodels` and `registry` records were created the moment the inference service was created, but the `instances` record was only created later after the SR2 pod was getting to Running state. Could this be why the controller could not find any running instances of SR2 for IS2 and it led to the `Specified runtime name not recognised` error?
- When the serving runtimes and inference services are deleted from the cluster, I noticed that the `vmodels` and `registry` records for the inference services were not deleted from etcd. Is this behaviour expected?
