### ISSUE TITLE
Status URL customization for ModelMesh inference services

### ISSUE THREAD

**Issue by danilopeixoto** [kserve/modelmesh-serving#384]
**Is your feature request related to a problem? If so, please describe.**

For `modelmesh-serving`  services using ingress, administrators are unable to configure the URL provided by the inference service status.

**Describe your proposed solution**

The URL provides users with a convenient way to obtain the inference service URL and send requests. When using ingress, administrators cannot change inference service status URL.

The proposal introduces the ingress configuration to `model-serving-config-defaults`. Examples:

Configuration (default):
```yaml
ingress:
  ingressDomain: example.com
  domainTemplate: {{ .ServiceName }}.{{ .Namespace }}:{{ .ServicePort }}
  urlScheme: grpc
```

Output:

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: modelmesh-test
  namespace: kserve-modelmesh-user
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
status:
  components:
    predictor:
      grpcUrl: grpc://modelmesh-serving.kserve-modelmesh-user:8033
      restUrl: http://modelmesh-serving.kserve-modelmesh-user:8008
      url: grpc://modelmesh-serving.kserve-modelmesh-user:8033
  url: grpc://modelmesh-serving.kserve-modelmesh-user:8033
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      protocolVersion: v2
      runtime: mlserver-0.x
      storageUri: s3://path/to/model
```

Configuration:

```yaml
ingress:
  ingressDomain: example.com
  domainTemplate: {{ .ServiceName }}.{{ .Namespace }}.{{ .IngressDomain }}
  urlScheme: https
```

Output:

```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: modelmesh-test
  namespace: kserve-modelmesh-user
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
status:
  components:
    predictor:
      grpcUrl: grpc://modelmesh-serving.kserve-modelmesh-user:8033
      restUrl: http://modelmesh-serving.kserve-modelmesh-user:8008
      url: grpc://modelmesh-serving.kserve-modelmesh-user:8033
  url: grpc://modelmesh-serving.kserve-modelmesh-user:8033
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      protocolVersion: v2
      runtime: mlserver-0.x
      storageUri: s3://path/to/model
```

**Describe alternatives you have considered**

In the future, the configuration can be used to automatically generate ingress objects.

**Additional context**

The proposed configuration is based on KServe ingress configuration in `inferenceservice-config`:

https://github.com/kserve/kserve/blob/master/config/configmap/inferenceservice.yaml
