### ISSUE TITLE
Investigate storage differences in Predictor vs InferenceService

### ISSUE THREAD

**Issue by pvaneck** [kserve/modelmesh-serving#4]
Currently, the way a user defines a storage location of a model varies between the MM `Predictor` and KFS `InferenceService`.

With the InferenceService, a user specifies a `storageUri` (ex: `s3://kfserving-examples/tf-models/mnist`).
With the Predictor, a user can specify  a `storage` object, but the `path` would be it's own key/value. Example:
```
path: tf-models/mnist
storage:
    s3:
      secretKey: my_storage
      bucket: kfserving-examples
```
In some cases, the storage object can be omitted in the case of custom runtimes managing their own storage.

Would be good to examine the advantages and disadvantages of these approaches and see how we may consolidate.
