### ISSUE TITLE
[Feature] Expose Triton metrics

### ISSUE THREAD

**Issue by WaterKnight1998** [kserve/modelmesh-serving#409]
I have trying to load Triton Inference Server metrics in prometheus too because I want execution count per model. For that purpose I used:
```yaml
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    maxLoadingConcurrency: "2"
  labels:
    app.kubernetes.io/instance: modelmesh-controller
    app.kubernetes.io/managed-by: modelmesh-controller
    app.kubernetes.io/name: modelmesh-controller
    name: modelmesh-serving-triton-2.x-SR
  name: triton-2.x
  namespace: modelmesh
spec:
  builtInAdapter:
    memBufferBytes: 134217728
    modelLoadingTimeoutMillis: 90000
    runtimeManagementPort: 8001
    serverType: triton
    env:
    - name: CONTAINER_MEM_REQ_BYTES
      value: "12884901888" # Works for T4
    - name: MODELSIZE_MULTIPLIER
      value: "2"
  containers:
  - args:
    - -c
    - 'mkdir -p /models/_triton_models; chmod 777 /models/_triton_models; exec tritonserver
      "--model-repository=/models/_triton_models" "--model-control-mode=explicit"
      "--strict-model-config=false" "--strict-readiness=false" "--allow-http=true"
      "--allow-sagemaker=false" 
      "--allow-metrics=true" "--allow-gpu-metrics=true" "--allow-gpu-metrics=true" "--metrics-port=3333"'
    command:
    - /bin/sh
    image: nvcr.io/nvidia/tritonserver:23.04-py3
    ports:
    - containerPort: 3333
      protocol: TCP
    livenessProbe:
      exec:
        command:
        - curl
        - --fail
        - --silent
        - --show-error
        - --max-time
        - "9"
        - http://localhost:8000/v2/health/live
      initialDelaySeconds: 5
      periodSeconds: 30
      timeoutSeconds: 10
    name: triton
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        cpu: 500m
        memory: 1Gi
        nvidia.com/gpu: 1
```

and 

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: triton-metrics-monitor
  namespace: modelmesh
spec:
  selector:
    matchLabels:
      name: modelmesh-serving-triton-2.x 
  namespaceSelector:
    matchNames:
      - modelmesh
  podMetricsEndpoints:
    - port: "3333"
      interval: 30s
      path: /metrics
      scheme: http
```

However, prometheus is not able to retrieve those metrics. I have treid to do a port forward to 3333 and accessing localhost:3333/metrics returns the metrics.

Probably is because the InferenceServer gets the following annotations
```
prometheus.io/path: /metrics
prometheus.io/port: 2112
prometheus.io/scheme: https
prometheus.io/scrape: true
```

I don't know if your controller is in charge of applying those annotations. Thanks in advance!

**Comment by WaterKnight1998** [comment]
Fixed by giving port a name:

```yaml
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    maxLoadingConcurrency: "2"
  labels:
    app.kubernetes.io/instance: modelmesh-controller
    app.kubernetes.io/managed-by: modelmesh-controller
    app.kubernetes.io/name: modelmesh-controller
    name: modelmesh-serving-triton-2.x-SR
  name: triton-2.x
  namespace: modelmesh
spec:
  builtInAdapter:
    memBufferBytes: 134217728
    modelLoadingTimeoutMillis: 90000
    runtimeManagementPort: 8001
    serverType: triton
    env:
    - name: CONTAINER_MEM_REQ_BYTES
      value: "12884901888" # Works for T4
    - name: MODELSIZE_MULTIPLIER
      value: "2"
  containers:
  - args:
    - -c
    - 'mkdir -p /models/_triton_models; chmod 777 /models/_triton_models; exec tritonserver
      "--model-repository=/models/_triton_models" "--model-control-mode=explicit"
      "--strict-model-config=false" "--strict-readiness=false" "--allow-http=true"
      "--allow-sagemaker=false" 
      "--allow-metrics=true" "--allow-gpu-metrics=true" "--allow-gpu-metrics=true" "--metrics-port=3333"'
    command:
    - /bin/sh
    image: nvcr.io/nvidia/tritonserver:23.04-py3
    ports:
    - containerPort: 3333
      protocol: TCP
      name: http-metrics
    livenessProbe:
      exec:
        command:
        - curl
        - --fail
        - --silent
        - --show-error
        - --max-time
        - "9"
        - http://localhost:8000/v2/health/live
      initialDelaySeconds: 5
      periodSeconds: 30
      timeoutSeconds: 10
    name: triton
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        cpu: 500m
        memory: 1Gi
        nvidia.com/gpu: 1
```

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: triton-metrics-monitor
  namespace: modelmesh-runtimes
spec:
  selector:
    matchLabels:
      name: modelmesh-serving-triton-2.x 
  namespaceSelector:
    matchNames:
      - modelmesh
  podMetricsEndpoints:
    - port: "http-metrics"
      interval: "30s"
      path: /metrics
      scheme: "http"
    - path: /metrics
      port: "prometheus"
      scheme: "https"
      tlsConfig:
        insecureSkipVerify: true
```
